global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'flink-jobmanager'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['jobmanager:8081']

  - job_name: 'flink-taskmanager'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['taskmanager:8081']
